AWSTemplateFormatVersion: '2010-09-09'
Description: GPTa Application
Resources:
  EventTable:
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::Serverless::SimpleTable
  GetEvents:
    Properties:
      CodeUri: s3://gpta2017/22f5eb0dfce935a5bbeca2e32d4ed308
      Environment:
        Variables:
          TABLE_NAME:
            Ref: EventTable
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /events
          Type: Api
      Handler: getEvents.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs4.3
      Timeout: 10
    Type: AWS::Serverless::Function
  GetEventsById:
    Properties:
      CodeUri: s3://gpta2017/22f5eb0dfce935a5bbeca2e32d4ed308
      Environment:
        Variables:
          TABLE_NAME:
            Ref: EventTable
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /events/{id}
          Type: Api
      Handler: getEvents.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs4.3
      Timeout: 10
    Type: AWS::Serverless::Function
  GetPrograms:
    Properties:
      CodeUri: s3://gpta2017/22f5eb0dfce935a5bbeca2e32d4ed308
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ProgramTable
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /events/{id}/programs
          Type: Api
      Handler: getPrograms.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs4.3
      Timeout: 10
    Type: AWS::Serverless::Function
  ProgramTable:
    Properties:
      PrimaryKey:
        Name: eventid
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
