AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GPTA Ticket Application

Resources:
  GetEvents:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getTickets.handler
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBReadOnlyAccess
      CodeUri: src
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref TicketTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /tickets
            Method: get


  TicketTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
         Name: id
         Type: String
      ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5
