AWSTemplateFormatVersion: '2010-09-09'
Description: GPTA Ticket Application
Resources:
  AddTicket:
    Properties:
      CodeUri: s3://gpta2019/5fb0bd890d51b5c8c8a95f67c8996db1
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TicketTable
      Events:
        PostResource:
          Properties:
            Method: post
            Path: /tickets
          Type: Api
      Handler: addTicket.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
  CheckIn:
    Properties:
      CodeUri: s3://gpta2019/5fb0bd890d51b5c8c8a95f67c8996db1
      Environment:
        Variables:
          TABLETICKETCHECKIN:
            Ref: TicketCheckIn
      Events:
        PostResource:
          Properties:
            Method: post
            Path: /tickets/checkins
          Type: Api
      Handler: checkIn.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
  DeleteTickets:
    Properties:
      CodeUri: s3://gpta2019/5fb0bd890d51b5c8c8a95f67c8996db1
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TicketTable
      Events:
        PostResource:
          Properties:
            Method: delete
            Path: /tickets
          Type: Api
      Handler: deleteAllTickets.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
  GetCheckIns:
    Properties:
      CodeUri: s3://gpta2019/5fb0bd890d51b5c8c8a95f67c8996db1
      Environment:
        Variables:
          TABLETICKETCHECKIN:
            Ref: TicketCheckIn
      Events:
        PostResource:
          Properties:
            Method: get
            Path: /tickets/checkins
          Type: Api
      Handler: getCheckIns.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
  GetTickets:
    Properties:
      CodeUri: s3://gpta2019/5fb0bd890d51b5c8c8a95f67c8996db1
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TicketTable
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /tickets
          Type: Api
      Handler: getTickets.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
  SummaryTickets:
    Properties:
      CodeUri: s3://gpta2019/5fb0bd890d51b5c8c8a95f67c8996db1
      Environment:
        Variables:
          TABLETICKETCHECKIN:
            Ref: TicketCheckIn
          TABLE_NAME:
            Ref: TicketTable
      Events:
        PostResource:
          Properties:
            Method: get
            Path: /tickets/summary
          Type: Api
      Handler: getTicketsSummary.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
  TicketCheckIn:
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::Serverless::SimpleTable
  TicketTable:
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
